apiVersion: v1
kind: Namespace
metadata:
  name: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/metallb
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        - ../../values/apps.yaml
  syncPolicy:
    automated: {} 
