apiVersion: v1
kind: Namespace
metadata:
  name: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/metallb
    repoURL: https://github.com/anrav8/argoapp.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - ../../values/apps.yaml
  syncPolicy:
    automated: {} 
